		<nav id="sidebar">
				<div class="p-4 pt-5">
		  		<a href="#" class="img logo rounded-circle mb-5" style="background-image: url(images/logo.jpg);"></a>
	        <ul class="list-unstyled components mb-5">
	          <li>
              <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Gestion des voitures</a>
              <ul class="collapse list-unstyled" id="pageSubmenu">
                <li><a href="#">Ajouter une voiture</a></li>
                <li><a href="#">Modifier une voiture</a></li>
                <li><a href="#">Supprimer une voiture</a></li>
              </ul>
	          </li>
	          <li><a href="#">Gestion des clients</a></li>
              <li><a href="#">Gestion des réservations</a></li>
              <li><a href="#">Gestion des factures</a></li>
	        </ul>
			<br><br><br>
	        <div class="footer">
				<p>Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with by <a href="https://colorlib.com" target="_blank">Colorlib.com</a>
	        </div>

	      </div>
    	</nav>

        <!-- Page Content  -->
      <div id="content" class="p-4 p-md-5">

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">

            <button type="button" id="sidebarCollapse" class="btn btn-primary">
              <i class="fa fa-bars"></i>
              <span class="sr-only">Toggle Menu</span>
            </button>
            <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fa fa-bars"></i>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="nav navbar-nav ml-auto">
                <li class="nav-item"><a class="nav-link" href="#">Déconnexion</a></li>
              </ul>
            </div>
          </div>
        </nav>